version: '3.9'

services:
  radarr:
    image: yogarine/radarr:${RADARR_VERSION}
    build:
      context: .
      target: radarr
      args:
        RADARR_VERSION: "${RADARR_VERSION}"
    volumes:
      - "radarr-data:/home/radarr/.config/Radarr:cached"
    labels:
      traefik.port: '7878'

volumes:
  radarr-data:
